### ISSUE TITLE
out of bound array access

### ISSUE THREAD

**Issue by BroCanDo** [NTAP/quant#13]
https://github.com/NTAP/quant/blob/150580aa495ae7e79a1331267c52f0491e59b017/lib/src/tls.c#L978
Hi,

```
      do {
            X509 * const x509 = PEM_read_X509(fp, 0, 0, 0);
            if (x509 == 0)
                break;
            tls_certs[i].len = (size_t)i2d_X509(x509, &tls_certs[i].base);
            X509_free(x509);
        } while (i++ < TLS_MAX_CERTS);
```

this code fragment may crash the application. i++ increments the variable after the comparison. This may mean, that i can hold the value TLS_MAX_CERTS and thus cause the application to crash.

Best Regards

**Comment by larseggert** [comment]
Thanks for the report - fixed
