### ISSUE TITLE
ev_async_stop is not called in free_conn

### ISSUE THREAD

**Issue by futile** [NTAP/quant#16]
`free_conn` (https://github.com/NTAP/quant/blob/14/lib/src/conn.c#L1287) does not call `ev_async_stop` prior to freeing the `ev_async` (https://github.com/NTAP/quant/blob/14/lib/src/conn.c#L1326).

However, it is initialized in `new_conn` (https://github.com/NTAP/quant/blob/14/lib/src/conn.c#L1247) with a value inside the `conn` that is free'd, so there is now a dangling pointer inside the loop.

This doesn't crash because it's an async watcher, and it never gets triggered again, and it seems that `libev` never looks at it again too closely, or otherwise it would touch upon free'd memory.

**Comment by larseggert** [comment]
Thanks for the report. Will take a look when I have some cycles for quant.
