### ISSUE TITLE
build

### ISSUE THREAD

**Issue by pfeatherstone** [NTAP/quant#29]
Running the cmake build script fails with 

cp: <path-to-repo>/quant/build/external/lib' is not a directory
external/CMakeFiles/picotls.dir/build.make:73: recipe for target 'external/picotls-prefix/src/picotls-stamp/picotls-install' failed

**Comment by larseggert** [comment]
Which platform are you on, and can you post the full `cmake` output please?

**Comment by pfeatherstone** [comment]
I’m on Ubuntu 16, amd64. I will send you the output when I get home. Thanks

**Comment by larseggert** [comment]
I think this should be fixed with ef563bd6

**Comment by pfeatherstone** [comment]
There is a different problem now. This is the current build:

peter@pf-ubuntu-dev:~/Downloads/quant_update$ cd build/
peter@pf-ubuntu-dev:~/Downloads/quant_update/build$ cmake -DCMAKE_BUILD_TYPE=Release ..
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for benchmark::Initialize
-- Looking for benchmark::Initialize - not found
-- Looking for ProfilerStart
-- Looking for ProfilerStart - not found
-- Looking for htobe64
-- Looking for htobe64 - found
-- Looking for htobe64
-- Looking for htobe64 - not found
-- Found OpenSSL: /usr/lib/x86_64-linux-gnu/libcrypto.so (found version "1.0.2g")  
-- Performing Test _pipe
-- Performing Test _pipe - Success
-- Performing Test _march_native
-- Performing Test _march_native - Success
-- Performing Test _Wextra
-- Performing Test _Wextra - Success
-- Performing Test _Wpedantic
-- Performing Test _Wpedantic - Success
-- Performing Test _Weverything
-- Performing Test _Weverything - Failed
-- Performing Test _Werror
-- Performing Test _Werror - Success
-- Performing Test _fcolor_diagnostics
-- Performing Test _fcolor_diagnostics - Failed
-- Performing Test _fdiagnostics_color_always
-- Performing Test _fdiagnostics_color_always - Success
-- Performing Test _Wno_missing_braces
-- Performing Test _Wno_missing_braces - Success
-- Performing Test _Wno_gnu_statement_expression
-- Performing Test _Wno_gnu_statement_expression - Success
-- Performing Test _Wno_extended_offsetof
-- Performing Test _Wno_extended_offsetof - Success
-- Performing Test _Wno_redundant_parens
-- Performing Test _Wno_redundant_parens - Success
-- Performing Test _Wno_switch_enum
-- Performing Test _Wno_switch_enum - Success
-- Performing Test _Wno_missing_field_initializers
-- Performing Test _Wno_missing_field_initializers - Success
-- Performing Test _Wno_disabled_macro_expansion
-- Performing Test _Wno_disabled_macro_expansion - Success
-- Performing Test _Wno_cpp
-- Performing Test _Wno_cpp - Success
-- Performing Test _fcomment_block_commands_dotfile
-- Performing Test _fcomment_block_commands_dotfile - Failed
-- Performing Test _Wno_c__98_compat
-- Performing Test _Wno_c__98_compat - Success
-- Performing Test _Wno_global_constructors
-- Performing Test _Wno_global_constructors - Success
-- Performing Test _Wno_c99_extensions
-- Performing Test _Wno_c99_extensions - Success
-- Found http-parser: /usr/lib/x86_64-linux-gnu/libhttp_parser.so  
-- Found Doxygen: /usr/bin/doxygen (found version "1.8.11") found components:  doxygen missing components:  dot
-- Found Git: /usr/bin/git (found version "2.7.4") 
-- Found Hg: /usr/bin/hg (found version "3.7.3") 
-- Found libev: /usr/lib/x86_64-linux-gnu/libev.so  
-- Configuring done
CMake Warning (dev) in bin/CMakeLists.txt:
  Policy CMP0083 is not set: Add PIE options when linking executable.  Run
  "cmake --help-policy CMP0083" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) in bin/CMakeLists.txt:
  Policy CMP0083 is not set: Add PIE options when linking executable.  Run
  "cmake --help-policy CMP0083" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) in test/CMakeLists.txt:
  Policy CMP0083 is not set: Add PIE options when linking executable.  Run
  "cmake --help-policy CMP0083" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) in test/CMakeLists.txt:
  Policy CMP0083 is not set: Add PIE options when linking executable.  Run
  "cmake --help-policy CMP0083" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Generating done
-- Build files have been written to: /home/peter/Downloads/quant_update/build
peter@pf-ubuntu-dev:~/Downloads/quant_update/build$ make
Scanning dependencies of target picotls
[  4%] Creating directories for 'picotls'
[  4%] Performing download step (git clone) for 'picotls'
Cloning into 'picotls'...
Note: checking out 'd94a67d4d9733fa7b72c331d238c6160298d39b3'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at d94a67d... add missing C++ guards
Submodule 'deps/picotest' (https://github.com/h2o/picotest.git) registered for path 'deps/picotest'
Cloning into 'deps/picotest'...
Submodule path 'deps/picotest': checked out 'f390562fd4d6919807441721ec05b08f6d8c8d9c'
[  8%] No patch step for 'picotls'
[ 12%] Performing update step for 'picotls'
[ 16%] Performing configure step for 'picotls'
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- Checking for module 'libbrotlidec'
--   No package 'libbrotlidec' found
-- Checking for module 'libbrotlienc'
--   No package 'libbrotlienc' found
-- Found OpenSSL: /usr/lib/x86_64-linux-gnu/libcrypto.so (found version "1.0.2g")  
CMake Warning at CMakeLists.txt:48 (MESSAGE):
  Enabling OpenSSL support


-- Configuring done
-- Generating done
-- Build files have been written to: /home/peter/Downloads/quant_update/build/external/picotls-prefix/src/picotls-build
[ 20%] Performing build step for 'picotls'
Scanning dependencies of target test-openssl.t
[  1%] Building C object CMakeFiles/test-openssl.t.dir/deps/micro-ecc/uECC.c.o
[  2%] Building C object CMakeFiles/test-openssl.t.dir/deps/cifra/src/aes.c.o
[  4%] Building C object CMakeFiles/test-openssl.t.dir/deps/cifra/src/blockwise.c.o
[  5%] Building C object CMakeFiles/test-openssl.t.dir/deps/cifra/src/chacha20.c.o
[  7%] Building C object CMakeFiles/test-openssl.t.dir/deps/cifra/src/chash.c.o
[  8%] Building C object CMakeFiles/test-openssl.t.dir/deps/cifra/src/curve25519.c.o
[ 10%] Building C object CMakeFiles/test-openssl.t.dir/deps/cifra/src/drbg.c.o
[ 11%] Building C object CMakeFiles/test-openssl.t.dir/deps/cifra/src/hmac.c.o
[ 13%] Building C object CMakeFiles/test-openssl.t.dir/deps/cifra/src/gcm.c.o
[ 14%] Building C object CMakeFiles/test-openssl.t.dir/deps/cifra/src/gf128.c.o
[ 15%] Building C object CMakeFiles/test-openssl.t.dir/deps/cifra/src/modes.c.o
[ 17%] Building C object CMakeFiles/test-openssl.t.dir/deps/cifra/src/poly1305.c.o
[ 18%] Building C object CMakeFiles/test-openssl.t.dir/deps/cifra/src/sha256.c.o
[ 20%] Building C object CMakeFiles/test-openssl.t.dir/deps/cifra/src/sha512.c.o
[ 21%] Building C object CMakeFiles/test-openssl.t.dir/lib/cifra.c.o
[ 23%] Building C object CMakeFiles/test-openssl.t.dir/lib/uecc.c.o
[ 24%] Building C object CMakeFiles/test-openssl.t.dir/lib/asn1.c.o
[ 26%] Building C object CMakeFiles/test-openssl.t.dir/lib/pembase64.c.o
[ 27%] Building C object CMakeFiles/test-openssl.t.dir/deps/picotest/picotest.c.o
[ 28%] Building C object CMakeFiles/test-openssl.t.dir/t/picotls.c.o
In file included from /home/peter/Downloads/quant_update/build/external/picotls-prefix/src/picotls/t/picotls.c:28:0:
/home/peter/Downloads/quant_update/build/external/picotls-prefix/src/picotls/t/../lib/picotls.c: In function ‘send_client_hello’:
/home/peter/Downloads/quant_update/build/external/picotls-prefix/src/picotls/include/picotls.h:690:12: warning: ‘resumption_ticket’ may be used uninitialized in this function [-Wmaybe-uninitialized]
         if ((ret = ptls_buffer__do_pushv((buf), (src), (len))) != 0)                                                
            ^
In file included from /home/peter/Downloads/quant_update/build/external/picotls-prefix/src/picotls/t/picotls.c:32:0:
/home/peter/Downloads/quant_update/build/external/picotls-prefix/src/picotls/t/../lib/picotls.c:1408:46: note: ‘resumption_ticket’ was declared here
     ptls_iovec_t resumption_secret = {NULL}, resumption_ticket;
                                              ^
In file included from /home/peter/Downloads/quant_update/build/external/picotls-prefix/src/picotls/t/picotls.c:28:0:
/home/peter/Downloads/quant_update/build/external/picotls-prefix/src/picotls/include/picotls.h:690:12: warning: ‘*((void *)&resumption_ticket+8)’ may be used uninitialized in this function [-Wmaybe-uninitialized]
         if ((ret = ptls_buffer__do_pushv((buf), (src), (len))) != 0)                                                
            ^
In file included from /home/peter/Downloads/quant_update/build/external/picotls-prefix/src/picotls/t/picotls.c:32:0:
/home/peter/Downloads/quant_update/build/external/picotls-prefix/src/picotls/t/../lib/picotls.c:1408:46: note: ‘*((void *)&resumption_ticket+8)’ was declared here
     ptls_iovec_t resumption_secret = {NULL}, resumption_ticket;
                                              ^
[ 30%] Building C object CMakeFiles/test-openssl.t.dir/t/openssl.c.o
In file included from /home/peter/Downloads/quant_update/build/external/picotls-prefix/src/picotls/t/openssl.c:34:0:
/home/peter/Downloads/quant_update/build/external/picotls-prefix/src/picotls/t/../lib/openssl.c: In function ‘cipher_do_init’:
/home/peter/Downloads/quant_update/build/external/picotls-prefix/src/picotls/t/../lib/openssl.c:616:9: warning: variable ‘ret’ set but not used [-Wunused-but-set-variable]
     int ret;
         ^
/home/peter/Downloads/quant_update/build/external/picotls-prefix/src/picotls/t/../lib/openssl.c: In function ‘cipher_encrypt’:
/home/peter/Downloads/quant_update/build/external/picotls-prefix/src/picotls/t/../lib/openssl.c:643:26: warning: unused variable ‘ret’ [-Wunused-variable]
     int len = (int)_len, ret = EVP_EncryptUpdate(ctx->evp, output, &len, input, len);
                          ^
/home/peter/Downloads/quant_update/build/external/picotls-prefix/src/picotls/t/../lib/openssl.c: In function ‘aead_do_encrypt_init’:
/home/peter/Downloads/quant_update/build/external/picotls-prefix/src/picotls/t/../lib/openssl.c:682:9: warning: variable ‘ret’ set but not used [-Wunused-but-set-variable]
     int ret;
         ^
/home/peter/Downloads/quant_update/build/external/picotls-prefix/src/picotls/t/../lib/openssl.c: In function ‘aead_do_encrypt_update’:
/home/peter/Downloads/quant_update/build/external/picotls-prefix/src/picotls/t/../lib/openssl.c:698:19: warning: variable ‘ret’ set but not used [-Wunused-but-set-variable]
     int blocklen, ret;
                   ^
/home/peter/Downloads/quant_update/build/external/picotls-prefix/src/picotls/t/../lib/openssl.c: In function ‘aead_do_encrypt_final’:
/home/peter/Downloads/quant_update/build/external/picotls-prefix/src/picotls/t/../lib/openssl.c:711:19: warning: variable ‘ret’ set but not used [-Wunused-but-set-variable]
     int blocklen, ret;
                   ^
/home/peter/Downloads/quant_update/build/external/picotls-prefix/src/picotls/t/../lib/openssl.c: In function ‘aead_do_decrypt’:
/home/peter/Downloads/quant_update/build/external/picotls-prefix/src/picotls/t/../lib/openssl.c:729:19: warning: variable ‘ret’ set but not used [-Wunused-but-set-variable]
     int blocklen, ret;
                   ^
[ 31%] Linking C executable test-openssl.t
[ 31%] Built target test-openssl.t
Scanning dependencies of target picotls-core
[ 33%] Building C object CMakeFiles/picotls-core.dir/lib/picotls.c.o
In file included from /home/peter/Downloads/quant_update/build/external/picotls-prefix/src/picotls/lib/picotls.c:33:0:
/home/peter/Downloads/quant_update/build/external/picotls-prefix/src/picotls/lib/picotls.c: In function ‘send_client_hello’:
/home/peter/Downloads/quant_update/build/external/picotls-prefix/src/picotls/include/picotls.h:690:12: warning: ‘resumption_ticket’ may be used uninitialized in this function [-Wmaybe-uninitialized]
         if ((ret = ptls_buffer__do_pushv((buf), (src), (len))) != 0)                                                
            ^
/home/peter/Downloads/quant_update/build/external/picotls-prefix/src/picotls/lib/picotls.c:1408:46: note: ‘resumption_ticket’ was declared here
     ptls_iovec_t resumption_secret = {NULL}, resumption_ticket;
                                              ^
In file included from /home/peter/Downloads/quant_update/build/external/picotls-prefix/src/picotls/lib/picotls.c:33:0:
/home/peter/Downloads/quant_update/build/external/picotls-prefix/src/picotls/include/picotls.h:690:12: warning: ‘*((void *)&resumption_ticket+8)’ may be used uninitialized in this function [-Wmaybe-uninitialized]
         if ((ret = ptls_buffer__do_pushv((buf), (src), (len))) != 0)                                                
            ^
/home/peter/Downloads/quant_update/build/external/picotls-prefix/src/picotls/lib/picotls.c:1408:46: note: ‘*((void *)&resumption_ticket+8)’ was declared here
     ptls_iovec_t resumption_secret = {NULL}, resumption_ticket;
                                              ^
[ 34%] Building C object CMakeFiles/picotls-core.dir/lib/pembase64.c.o
[ 36%] Linking C static library libpicotls-core.a
[ 36%] Built target picotls-core
Scanning dependencies of target picotls-openssl
[ 37%] Building C object CMakeFiles/picotls-openssl.dir/lib/openssl.c.o
/home/peter/Downloads/quant_update/build/external/picotls-prefix/src/picotls/lib/openssl.c: In function ‘cipher_do_init’:
/home/peter/Downloads/quant_update/build/external/picotls-prefix/src/picotls/lib/openssl.c:616:9: warning: variable ‘ret’ set but not used [-Wunused-but-set-variable]
     int ret;
         ^
/home/peter/Downloads/quant_update/build/external/picotls-prefix/src/picotls/lib/openssl.c: In function ‘cipher_encrypt’:
/home/peter/Downloads/quant_update/build/external/picotls-prefix/src/picotls/lib/openssl.c:643:26: warning: unused variable ‘ret’ [-Wunused-variable]
     int len = (int)_len, ret = EVP_EncryptUpdate(ctx->evp, output, &len, input, len);
                          ^
/home/peter/Downloads/quant_update/build/external/picotls-prefix/src/picotls/lib/openssl.c: In function ‘aead_do_encrypt_init’:
/home/peter/Downloads/quant_update/build/external/picotls-prefix/src/picotls/lib/openssl.c:682:9: warning: variable ‘ret’ set but not used [-Wunused-but-set-variable]
     int ret;
         ^
/home/peter/Downloads/quant_update/build/external/picotls-prefix/src/picotls/lib/openssl.c: In function ‘aead_do_encrypt_update’:
/home/peter/Downloads/quant_update/build/external/picotls-prefix/src/picotls/lib/openssl.c:698:19: warning: variable ‘ret’ set but not used [-Wunused-but-set-variable]
     int blocklen, ret;
                   ^
/home/peter/Downloads/quant_update/build/external/picotls-prefix/src/picotls/lib/openssl.c: In function ‘aead_do_encrypt_final’:
/home/peter/Downloads/quant_update/build/external/picotls-prefix/src/picotls/lib/openssl.c:711:19: warning: variable ‘ret’ set but not used [-Wunused-but-set-variable]
     int blocklen, ret;
                   ^
/home/peter/Downloads/quant_update/build/external/picotls-prefix/src/picotls/lib/openssl.c: In function ‘aead_do_decrypt’:
/home/peter/Downloads/quant_update/build/external/picotls-prefix/src/picotls/lib/openssl.c:729:19: warning: variable ‘ret’ set but not used [-Wunused-but-set-variable]
     int blocklen, ret;
                   ^
[ 39%] Linking C static library libpicotls-openssl.a
[ 39%] Built target picotls-openssl
Scanning dependencies of target cli
[ 40%] Building C object CMakeFiles/cli.dir/t/cli.c.o
/home/peter/Downloads/quant_update/build/external/picotls-prefix/src/picotls/t/cli.c: In function ‘handle_connection’:
/home/peter/Downloads/quant_update/build/external/picotls-prefix/src/picotls/t/cli.c:153:29: warning: ignoring return value of ‘write’, declared with attribute warn_unused_result [-Wunused-result]
                             (void)write(sockfd, encbuf.base, encbuf.off);
                             ^
/home/peter/Downloads/quant_update/build/external/picotls-prefix/src/picotls/t/cli.c:160:29: warning: ignoring return value of ‘write’, declared with attribute warn_unused_result [-Wunused-result]
                             write(1, rbuf.base, rbuf.off);
                             ^
[ 42%] Building C object CMakeFiles/cli.dir/lib/pembase64.c.o
[ 43%] Linking C executable cli
[ 43%] Built target cli
Scanning dependencies of target picotls-minicrypto
[ 44%] Building C object CMakeFiles/picotls-minicrypto.dir/deps/micro-ecc/uECC.c.o
[ 46%] Building C object CMakeFiles/picotls-minicrypto.dir/deps/cifra/src/aes.c.o
[ 47%] Building C object CMakeFiles/picotls-minicrypto.dir/deps/cifra/src/blockwise.c.o
[ 49%] Building C object CMakeFiles/picotls-minicrypto.dir/deps/cifra/src/chacha20.c.o
[ 50%] Building C object CMakeFiles/picotls-minicrypto.dir/deps/cifra/src/chash.c.o
[ 52%] Building C object CMakeFiles/picotls-minicrypto.dir/deps/cifra/src/curve25519.c.o
[ 53%] Building C object CMakeFiles/picotls-minicrypto.dir/deps/cifra/src/drbg.c.o
[ 55%] Building C object CMakeFiles/picotls-minicrypto.dir/deps/cifra/src/hmac.c.o
[ 56%] Building C object CMakeFiles/picotls-minicrypto.dir/deps/cifra/src/gcm.c.o
[ 57%] Building C object CMakeFiles/picotls-minicrypto.dir/deps/cifra/src/gf128.c.o
[ 59%] Building C object CMakeFiles/picotls-minicrypto.dir/deps/cifra/src/modes.c.o
[ 60%] Building C object CMakeFiles/picotls-minicrypto.dir/deps/cifra/src/poly1305.c.o
[ 62%] Building C object CMakeFiles/picotls-minicrypto.dir/deps/cifra/src/sha256.c.o
[ 63%] Building C object CMakeFiles/picotls-minicrypto.dir/deps/cifra/src/sha512.c.o
[ 65%] Building C object CMakeFiles/picotls-minicrypto.dir/lib/cifra.c.o
[ 66%] Building C object CMakeFiles/picotls-minicrypto.dir/lib/minicrypto-pem.c.o
[ 68%] Building C object CMakeFiles/picotls-minicrypto.dir/lib/uecc.c.o
[ 69%] Building C object CMakeFiles/picotls-minicrypto.dir/lib/asn1.c.o
[ 71%] Linking C static library libpicotls-minicrypto.a
[ 71%] Built target picotls-minicrypto
Scanning dependencies of target test-minicrypto.t
[ 72%] Building C object CMakeFiles/test-minicrypto.t.dir/deps/micro-ecc/uECC.c.o
[ 73%] Building C object CMakeFiles/test-minicrypto.t.dir/deps/cifra/src/aes.c.o
[ 75%] Building C object CMakeFiles/test-minicrypto.t.dir/deps/cifra/src/blockwise.c.o
[ 76%] Building C object CMakeFiles/test-minicrypto.t.dir/deps/cifra/src/chacha20.c.o
[ 78%] Building C object CMakeFiles/test-minicrypto.t.dir/deps/cifra/src/chash.c.o
[ 79%] Building C object CMakeFiles/test-minicrypto.t.dir/deps/cifra/src/curve25519.c.o
[ 81%] Building C object CMakeFiles/test-minicrypto.t.dir/deps/cifra/src/drbg.c.o
[ 82%] Building C object CMakeFiles/test-minicrypto.t.dir/deps/cifra/src/hmac.c.o
[ 84%] Building C object CMakeFiles/test-minicrypto.t.dir/deps/cifra/src/gcm.c.o
[ 85%] Building C object CMakeFiles/test-minicrypto.t.dir/deps/cifra/src/gf128.c.o
[ 86%] Building C object CMakeFiles/test-minicrypto.t.dir/deps/cifra/src/modes.c.o
[ 88%] Building C object CMakeFiles/test-minicrypto.t.dir/deps/cifra/src/poly1305.c.o
[ 89%] Building C object CMakeFiles/test-minicrypto.t.dir/deps/cifra/src/sha256.c.o
[ 91%] Building C object CMakeFiles/test-minicrypto.t.dir/deps/cifra/src/sha512.c.o
[ 92%] Building C object CMakeFiles/test-minicrypto.t.dir/deps/picotest/picotest.c.o
[ 94%] Building C object CMakeFiles/test-minicrypto.t.dir/t/picotls.c.o
In file included from /home/peter/Downloads/quant_update/build/external/picotls-prefix/src/picotls/t/picotls.c:28:0:
/home/peter/Downloads/quant_update/build/external/picotls-prefix/src/picotls/t/../lib/picotls.c: In function ‘send_client_hello’:
/home/peter/Downloads/quant_update/build/external/picotls-prefix/src/picotls/include/picotls.h:690:12: warning: ‘resumption_ticket’ may be used uninitialized in this function [-Wmaybe-uninitialized]
         if ((ret = ptls_buffer__do_pushv((buf), (src), (len))) != 0)                                                
            ^
In file included from /home/peter/Downloads/quant_update/build/external/picotls-prefix/src/picotls/t/picotls.c:32:0:
/home/peter/Downloads/quant_update/build/external/picotls-prefix/src/picotls/t/../lib/picotls.c:1408:46: note: ‘resumption_ticket’ was declared here
     ptls_iovec_t resumption_secret = {NULL}, resumption_ticket;
                                              ^
In file included from /home/peter/Downloads/quant_update/build/external/picotls-prefix/src/picotls/t/picotls.c:28:0:
/home/peter/Downloads/quant_update/build/external/picotls-prefix/src/picotls/include/picotls.h:690:12: warning: ‘*((void *)&resumption_ticket+8)’ may be used uninitialized in this function [-Wmaybe-uninitialized]
         if ((ret = ptls_buffer__do_pushv((buf), (src), (len))) != 0)                                                
            ^
In file included from /home/peter/Downloads/quant_update/build/external/picotls-prefix/src/picotls/t/picotls.c:32:0:
/home/peter/Downloads/quant_update/build/external/picotls-prefix/src/picotls/t/../lib/picotls.c:1408:46: note: ‘*((void *)&resumption_ticket+8)’ was declared here
     ptls_iovec_t resumption_secret = {NULL}, resumption_ticket;
                                              ^
[ 95%] Building C object CMakeFiles/test-minicrypto.t.dir/t/minicrypto.c.o
[ 97%] Building C object CMakeFiles/test-minicrypto.t.dir/lib/asn1.c.o
[ 98%] Building C object CMakeFiles/test-minicrypto.t.dir/lib/pembase64.c.o
[100%] Linking C executable test-minicrypto.t
[100%] Built target test-minicrypto.t
[ 24%] Performing install step for 'picotls'
[ 28%] Completed 'picotls'
[ 28%] Built target picotls
Scanning dependencies of target common
[ 32%] Building C object lib/CMakeFiles/common.dir/src/pkt.c.o
In file included from /home/peter/Downloads/quant_update/lib/src/pkt.c:43:0:
/home/peter/Downloads/quant_update/lib/src/conn.h:40:19: fatal error: khash.h: No such file or directory
compilation terminated.
lib/CMakeFiles/common.dir/build.make:62: recipe for target 'lib/CMakeFiles/common.dir/src/pkt.c.o' failed
make[2]: *** [lib/CMakeFiles/common.dir/src/pkt.c.o] Error 1
CMakeFiles/Makefile2:768: recipe for target 'lib/CMakeFiles/common.dir/all' failed
make[1]: *** [lib/CMakeFiles/common.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2


It's worth mentioning i'm using cmake version 3.13 and gcc 5.4.0.

Many thanks

**Comment by larseggert** [comment]
You need to give `git clone` the `--recurse-submodules` option. Or, in your existing clone, do `git submodule update --init --recursive`.

**Comment by pfeatherstone** [comment]
All fixed. Thank you
