### ISSUE TITLE
q_rx_ready returns pre-existings connection

### ISSUE THREAD

**Issue by pfeatherstone** [NTAP/quant#33]
Calling q_rx_ready sometimes returns a pre-existing connection

**Comment by larseggert** [comment]
What do you mean by "pre-existing"? `q_rx_ready()` returns a list of connections that have at least one stream that has unread data in it.

**Comment by larseggert** [comment]
It's meant to be similar to `poll()` or `select()`, yes. Sorry for the lack of documentation on the API - it's been changing, and so I didn't spent time on it yet. Also, it will likely continue to change.

**Comment by pfeatherstone** [comment]
Ok thank you. That clarifies it.
