### ISSUE TITLE
Client example missing "-l" parameter

### ISSUE THREAD

**Issue by JorisHerbots** [NTAP/quant#34]
The `client` example in `bin` returns the following when using the `-l log` option:

> [belbs@helheim bin]$ ./client -l /tmp/test index.html
./client: invalid option -- 'l'
client [options] URL
	[-i interface]	interface to run over; default lo
	[-s cache]	TLS 0-RTT state cache; default /tmp/test
	[-l log]	log file for TLS keys; default /tmp/quant-tlslog
	[-t timeout]	idle timeout in seconds; default 1
	[-c]		verify TLS certificates; default false
	[-u]	update TLS keys; default false
	[-3]		send a static H3 request; default false

The problem seems to be located in the `client.c` file:
https://github.com/NTAP/quant/blob/a738ea9da013b2523d71108c1ef3cca05a69e3ac/bin/client.c#L270
Adding `l:` to the getopt option string results in correct behaviour.

**Comment by larseggert** [comment]
Thanks, should be fixed now
