### ISSUE TITLE
performance: transfer rate decreases over time

### ISSUE THREAD

**Issue by hoang-tranviet** [NTAP/quant#38]
Hello,

I ran a simple benchmark test between two machines in LAN with the latest master branch (release build) with the socket backend, and observed the rate started at ~400Mbps but then dropped quickly to ~90Mbps during the first few seconds.

perf report on the server shows these hot functions: 

```
perf report -U
# Children      Self  Command  Shared Object      Symbol                                        
    35.72%    35.57%  server   server             [.] pm_by_nr(_splay)
            |
            ---pm_by_nr(_splay)

    28.90%    28.79%  server   server             [.] find_sent_pkt
            |
            ---find_sent_pkt

    17.43%    17.35%  server   server             [.] diet_find
            |
            ---diet_find

```

Might that be related to the inflation of un-acked data ranges on the sending side?

By the way, I hit the limit of ~100MB transfer size (complained by either `w_iov_sq_len()` or `w_alloc_iov()`), does this also happen with netmap or is there any workaround?

Thanks,

Hoang

**Comment by larseggert** [comment]
I think there are some subtle remaining bugs regarding congestion control and retransmissions, esp. for long bulk transfers. I'd be happy to merge PRs if you can track down some of them.

Regarding the 100MB limit, you probably need to increase the `num_bufs` parameter passed to `q_init()`.

**Comment by larseggert** [comment]
I made `num_bufs` a command line argument in b9be736e67ba3f0eca8a850fa6732315659efb48

**Comment by hoang-tranviet** [comment]
Thanks for the tip and this patch.

I want to figure out the issue though not sure I have time...

**Comment by larseggert** [comment]
I fixed a bug related to maintaining ACK ranges, would you test again with the latest master?

**Comment by hoang-tranviet** [comment]
Now it is consistently above 600 Mbps on the same machines, thanks for nice work :)

**Comment by larseggert** [comment]
There are more fixes on the latest master that should further increase throughput.

**Comment by hoang-tranviet** [comment]
Thank Lars, 
I just found my time to test, now it is around ~680-690 Mbps on the same machines.
