### ISSUE TITLE
Issue only when redirecting server output to a file

### ISSUE THREAD

**Issue by hoang-tranviet** [NTAP/quant#41]
Hello,

I don't know if this is due to my lack of sleep or it is a real issue.

When I run quant server (latest commit afc00e9d274, Debug mode) with no output redirection, it works:

    ./bin/server -d /dev/shm/ -b 500000

When I run it with redirection:

    ./bin/server -d /dev/shm/ -b 500000 &> /tmp/quant-server-log

, the connection was established but then does not work, you can see the output here (view it colorfully with `less -R`):
[server.log](https://send.firefox.com/download/bf8dfd3f9e/#m9XwNxVLLsGvUUvDETdxGA
)
And it seems Release mode does not work either.

Is there any possibility some file descriptor got messed up in my case?

Thanks,

**Comment by larseggert** [comment]
I can't seem to reproduce this, but I will try again on Monday. What URL (how many bytes) are you transferring, and is this over localhost, with the socket backend or netmap?

**Comment by hoang-tranviet** [comment]
I ran test over a Gigabit link, with 500 MB of huge index.html in /dev/shm/
It is over the socket backend.

    ./bin/client -i enp16s0f0 https://42.2.1.1:4433

Will try with URL instead when I have time.

**Comment by larseggert** [comment]
You can simply do https://42.2.1.1:4433/*<n>* where *<n>* is a number of bytes. See https://github.com/NTAP/quant/wiki

**Comment by larseggert** [comment]
@hoang-tranviet can you still reproduce the issue?

**Comment by hoang-tranviet** [comment]
I am closing the issue, will reopen it if seeing it again. 
Thanks.
