### ISSUE TITLE
Threadsafety question

### ISSUE THREAD

**Issue by DarkCaster** [NTAP/quant#43]
Hello! Thanks for your excellent work!
I'm trying to use your library in my project, and I have a question: is quant library thread-safe in any degree ?
Should I use external locking on q_bind\q_ready\q_accept (or any other) methods ? Can I run multiple independent server instances simultaneously, produced with multiple q_init calls ?

**Comment by larseggert** [comment]
Nope, it's not. And there are global variables that mean only only one instance per process can be run. Happy to accept PRs :-)
