### ISSUE TITLE
Get socket-handle

### ISSUE THREAD

**Issue by jakobod** [NTAP/quant#50]
Hi!
We are thinking about using this quic-stack in a C++-Framework. Since our network-design depends on epoll and the resulting events that come with it we need to be able to get the socket-handle.
I was looking around the interface and couldn't find such a function to get the created handle from the lib/warpcore-stack. Is there any way that I'm missing, or is it really not possible to get the handle?

**Comment by larseggert** [comment]
`w_fd()` gets you a socket handle
