### ISSUE TITLE
libbrotli-dev not documented but necessary for cmake

### ISSUE THREAD

**Issue by bortzmeyer** [NTAP/quant#58]
For the dependencies on a Debian system, you should add libbrotli-dev in the documentation.

**Comment by larseggert** [comment]
Really, the build fails for you? When I build on Debian and brotli isn't there, picotls simply won't include the related support. Could you post the console log of your failing build?

**Comment by bortzmeyer** [comment]
You are certainly right, I cannot reproduce the error anymore. Sorry.

**Comment by larseggert** [comment]
Great!
