### ISSUE TITLE
get "client.c:223 getaddrinfo: Address family for hostname not supported" while launching the client

### ISSUE THREAD

**Issue by Winters123** [NTAP/quant#62]
Hi, I'm on `7a4dc63` and keep getting this error from the 2nd round when I launch the client by:
```
./bin/client (or client-warp) -b 50000 -r 10 -i ens3f1 http://192.168.0.1:4433/10000000
```
```
        main client.c:607 read 63360 bytes in 0.000 sec (0.000 b/s) on conn 50b32a7b2c6e151777c3fbe53c25993f8b31 strm 4
        free_stream stream.c:141 freeing strm 4 on clnt conn 1:73611dc3
        main client.c:546 client retrieving http://192.168.0.1:4433/10000000
        get_addr client.c:223 getaddrinfo: Address family for hostname not supported
        main client.c:546 client retrieving http://192.168.0.1:4433/10000000
        get_addr client.c:223 getaddrinfo: Address family for hostname not supported
        main client.c:546 client retrieving http://192.168.0.1:4433/10000000
        get_addr client.c:223 getaddrinfo: Address family for hostname not supported
```
It looks like the the problem is within the IP addr configuration. But I checked the IP addr of both the server and client and they both work fine (can ping each other before/after the test). Not sure if I'm doing right here.

**Comment by larseggert** [comment]
I think I just closed this, please retry.

**Comment by Winters123** [comment]
Just tried with both v4 and v6 addr on `ed266f1`, but unfortunately I still get the same problem.
I also read this [thread](https://bugzilla.redhat.com/show_bug.cgi?id=1485755) but even if I disabled IPv4 addr, the same errors still pop up:
```
        main client.c:548 client retrieving http://[fe80::b696:91ff:fe31:964c]:4433/10000000
        get_addr client.c:227 getaddrinfo: Address family for hostname not supported
        main client.c:548 client retrieving http://[fe80::b696:91ff:fe31:964c]:4433/10000000
        get_addr client.c:227 getaddrinfo: Address family for hostname not supported
```

**Comment by larseggert** [comment]
You should be able to ignore this for now, it's not fatal?

**Comment by Winters123** [comment]
I thought it shouldn't be fatal, but after this error was reported, the client exited with error `-1`:
```
        get_addr client.c:227 getaddrinfo: Address family for hostname not supported
        main client.c:548 client retrieving http://[fe80::b696:91ff:fe31:964c]:4433/10000000
        get_addr client.c:227 getaddrinfo: Address family for hostname not supported
        main client.c:548 client retrieving http://[fe80::b696:91ff:fe31:964c]:4433/10000000
        get_addr client.c:227 getaddrinfo: Address family for hostname not supported
TOTAL: 0.000 b/s
0.021   main client.c:664 client exiting with -1
```
No other messages were printed out before it exited. Before the pull of yesterday, everything worked fine.

**Comment by larseggert** [comment]
Sorry about that. I won’t be getting to this before Monday, but you can comment out the error check and things should work. (It is just the lookup of the peer’s migration address which is failing, which is not used in your scenario anyway.

**Comment by larseggert** [comment]
So the reason here is probably that your v6 address `fe80::b696:91ff:fe31:964c` is invalid? Can you try with a well-formed v6 address?

**Comment by Winters123** [comment]
I'm not sure but giving it a try now. This morning I also noticed that before this was reported, there was another error msg which I don't understand and looks like it caused the connection's termination:
```
3.817   log_pkt pkt.c:150 RX from=192.168.0.1:4433 len=1456 ecn=ECT0 0x40=Short kyph=0 spin=0 dcid=0:277797f6 nr=8516
        dec_strm_data_blocked_frame frame.c:877 STREAM_DATA_BLOCKED id=4 lim=65535
        err_close conn.c:1643 off 65535 > 63359
        err_close conn.c:1627 ignoring new err 0x7; existing err is 0x6 (off 65535 > 63359)
3.817   log_pkt pkt.c:195 TX to=192.168.0.1:4433 0x60=Short kyph=0 spin=1 dcid=1:30a98a28 nr=52
        enc_ack_frame frame.c:1567 ACK 0x03=ECN lg=8515 delay=29 (232 usec) cnt=0 rng=45 [8470..515]
        enc_ack_frame frame.c:1598 ECN ect0=8293 ect1=0 ce=0
        enc_close_frame frame.c:1718 CONNECTION_CLOSE 0x1c=quic err=0x6 frame=0x15 rlen=17 reason=off 65535 > 63359
        log_sent_pkts conn.c:261 clnt conn 1:277797f6, Data unacked: 52
        q_read_stream quic.c:417 read 63360 new bytes in 45 bufs on clnt conn 1:277797f6 strm 4
3.818   log_pkt pkt.c:150 RX from=192.168.0.1:4433 len=17 ecn=ECT0 0x60=Short kyph=0 spin=1 dcid=0:277797f6 nr=8517
        dec_ack_frame frame.c:589 ACK 0x03=ECN lg=52 delay=21 (168 usec) cnt=0 rng=0 [52]
        dec_ack_frame frame.c:688 ECN ect0=53 ect1=0 ce=0
        dec_close_frame frame.c:761 CONNECTION_CLOSE 0x1d=app err=0x0 rlen=0 reason=
63360   -2232673.551719 "0.000 b/s"     http://192.168.0.1:4433/10000000
        main client.c:609 read 63360 bytes in 0.000 sec (0.000 b/s) on conn 17ba539e3f30801e strm 4
        free_stream stream.c:141 freeing strm 4 on clnt conn 1:277797f6
        main client.c:548 client-warp retrieving http://192.168.0.1:4433/10000000
        get_addr client.c:227 getaddrinfo: Address family for hostname not supported
```
This happened just before the original error that we discussed. 
Can you please have a look at it?

**Comment by larseggert** [comment]
How are you calling the client and server? (Command lines.)

**Comment by Winters123** [comment]
server: `./bin/server-warp (or server) -b 50000 -i ens3f0 -p 5533`
> And I'm using just one server for the test so the interface `ens3f0` was assigned to a different namespace `ns_1` and called with a prefix `ip netns exec ns_1`.
client: `./bin/client-warp (or client) -b 50000 -r 5 -i ens3f1 http://192.168.0.1:5533/10000000`

**Comment by larseggert** [comment]
OK, can you please try with the latest version? The error on parsing `STREAM_DATA_BLOCKED` should be fixed. Then we can see if that fixes your other issue as well.

**Comment by Winters123** [comment]
Thanks for it. Now its all fixed. I guess at first I misreported the error. The `ip addr error` should be a non-fatal one. Instead, it is the `stream_data_block` error that caused the connection termination.

**Comment by larseggert** [comment]
Glad it works again, and sorry for the instabilities
