### ISSUE TITLE
TLS ticket read error

### ISSUE THREAD

**Issue by arut** [NTAP/quant#69]
Several interop tests vs nginx fail with the following error:

```
client          | 0.048   reading TLS tickets from /tmp/quant-session
client          |         got TLS ticket server hq-29
client          | 0.048   read_tickets tls.c:1519 ABORT: assertion failed: 
client          |         len <= 256 
client          | SNI len 912697289634096720 too long [errno 2 = No such file or directory]
client          |         /lib/x86_64-linux-gnu/libasan.so.5(+0x6cd30) [0x7f10fe263d30]
client          |         util_die at /src/lib/deps/warpcore/lib/src/util.c:398
client          |         read_tickets at /src/lib/src/tls.c:1519
client          |         init_tls_ctx at /src/lib/src/tls.c:1701
client          |         q_init at /src/lib/src/quic.c:589 (discriminator 3)
client          |         main at /src/bin/client.c:519 (discriminator 4)
client          |         /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3) [0x7f10fd3d70b3]
client          |         _start at ??:?
```

What I believe is happening is the ticket file has some garbage after the first ticket.
Prior to that the ticket file was populated with some tickets a few times:
```
client          |         saving TLS tickets to /tmp/quant-session
client          |         writing TLS ticket for clnt conn 0:f90a3d01 (server hq-29)
client          |         saving TLS tickets to /tmp/quant-session
client          |         writing TLS ticket for clnt conn 0:f90a3d01 (server hq-29)
```

It seems to me the ticket file is not truncated by the moment of writing which may lead to some garbage left after the new ticket is written. That garbage is further interpreted as SNI len.

The fix could be adding the `O_TRUNC` flag here:
https://github.com/NTAP/quant/blob/b25900f81ba52a59095cc8fcf0b5f9da81eaf6f1/lib/src/tls.c#L1174

**Comment by larseggert** [comment]
Thanks for the report! Have you confirmed whether your patch fixes this?

**Comment by arut** [comment]
No I didn't. So far it's just my speculation.
I will probably try it when I have more time.

**Comment by larseggert** [comment]
I added `O_TRUNC` in the commit above, let me know if that fixed it? Otherwise please reopen.

**Comment by arut** [comment]
The new iteration went fine. The issue is fixed now. Thanks @larseggert!
