### ISSUE TITLE
Support for QUIC datagrams

### ISSUE THREAD

**Issue by JonasVautherin** [NTAP/quant#71]
I started looking into the library, but had a hard time finding documentation.

Does it support QUIC datagram? I couldn't find that in the codebase, so I suppose it doesn't. In that case, is support planned for it?

**Comment by larseggert** [comment]
No, there is no support planned for datagrams.

Also, quant is an R&D effort and not meant for production use.

**Comment by JonasVautherin** [comment]
Got it, thanks!
