### ISSUE TITLE
Decryption of QUIC packets using secret keys with wireshark

### ISSUE THREAD

**Issue by Yassine1394** [NTAP/quant#72]
I am trying to decrypt the QUIC packets with secret keys that I get from the client (or the server) by injecting those secret keys into wireshark. However, I receive the message of malformed packet on wireshark. Anyone can help with this?

**Comment by larseggert** [comment]
It's a known wireshark bug. Try the `-o` option to disable PMTUD, which quant does by padding with random data, which breaks wireshark
