### ISSUE TITLE
Basic setup of server and client configuration

### ISSUE THREAD

**Issue by simonasmulevicius** [NTAP/quant#73]
Good evening, 

I am also having a similar issue as @larseggert in https://github.com/NTAP/quant/issues/70#issuecomment-706662925_

After starting a server with the command (./bin/server) and then running a client with (./bin/client 127.0.0.1:4434) I get the following error:

0.075   q_init quic.c:685 quant/socket (epoll/sendmmsg/recvmmsg) 0.0.32/5d84d2a ready
        q_init quic.c:687 submit bug reports at https://github.com/NTAP/quant/issues
        read_tickets tls.c:1535 reading TLS tickets from /tmp/quant-session
        read_tickets tls.c:1540 could not read TLS tickets from /tmp/quant-session: No such file or directory
        init_tls_ctx tls.c:1770 picotls fusion is supported
0.077   main client.c:582 client retrieving 127.0.0.1:4434
        get client.c:252 http_parser_parse_url: the on_url callback failed
0.080   main client.c:699 client exiting with -1

However, you also mentioned that one would "need to start the server with a proper key and cert". Can you give us an example of how to do this?

**Comment by larseggert** [comment]
First, you need to give the client a proper URL to retrieve.

Second, you need to run bin/server. Check how bin/test.sh runs the server for an example.

**Comment by larseggert** [comment]
@simonasmulevicius did you manage to get it working?

**Comment by larseggert** [comment]
@simonasmulevicius ?

**Comment by larseggert** [comment]
Closing this. Please reopen if issue persists.
