### ISSUE TITLE
krng.h runtime error on mac osx

### ISSUE THREAD

**Issue by jeromelau1984** [NTAP/quant#76]
When I debug with test_conn, there was a runtime error as follow:
"./test/test_conn                                                                              ✔  1944  21:29:46
/Users/xxx/xxx/xxx/dev/quant/lib/deps/warpcore/lib/src/krng.h:15:21: runtime error: unsigned integer overflow: 13980888215752449660 + 11400714819323198485 cannot be represented in type 'unsigned long long'"
and my os information was "Darwin xxxMacBook-Pro.local 20.2.0 Darwin Kernel Version 20.2.0: Wed Dec  2 20:39:59 PST 2020; root:xnu-7195.60.75~1/RELEASE_X86_64 x86_64".
Hope for help, thx!
![image](https://user-images.githubusercontent.com/45782912/103898763-62a20f00-5130-11eb-9378-d3ec89b33eca.png)

**Comment by larseggert** [comment]
What compiler are you using to build? And can you post the output of a verbose build log? This false positive should be suppressed by something like `-fsanitize-blacklist=/Users/lars/Documents/Code/quant/lib/deps/warpcore/misc/sanitize-suppress.txt` so I am surprised you are seeing it.

**Comment by jeromelau1984** [comment]
My toolchain was
-- The C compiler identification is AppleClang 12.0.0.12000032
-- The CXX compiler identification is AppleClang 12.0.0.12000032，
and see the attachment for the compilation log.
[build.zip](https://github.com/NTAP/quant/files/5784896/build.zip)
