### ISSUE TITLE
Release/server

### ISSUE THREAD

**Issue by kabilumbu** [NTAP/quant#80]
Hello, 

When I try to run the server in the Release directory , the following error occurs 

0.004    :0 ABORT: DIED [errno 2 = No such file or directory]
        util_die at ??:?
        init_tls_ctx at ??:?
        q_init at ??:?
        main at ??:?
        /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xeb) [0x7fbf1ac9b09b]
        _start at ??:?
Aborted

**Comment by larseggert** [comment]
Please try a debug build, it has better diagnostic output. The release build is basically only for perf testing.

**Comment by larseggert** [comment]
I assume you have figured this out? Reopen if not.
