### ISSUE TITLE
reference paper

### ISSUE THREAD

**Issue by wild-birder** [NTAP/quant#81]
Dear Professor, I am a Chinese student and I am very interested in your Quant, but I am not very familiar with the workflow of Warpcore and QUIC due to my poor foundation. I hope you can provide me with some reference paper to help me understand your code.thanks a lot！

**Comment by larseggert** [comment]
There is no standalone paper on quant/warpcore. This one has a bit of a description: https://eggert.org/papers/2020-ndss-quic-iot.pdf
