### ISSUE TITLE
Problems with Ninja and server.c in /bin

### ISSUE THREAD

**Issue by sercankoc** [NTAP/quant#82]
Hello Mr. Eggert,

I am having some trouble using your server in the /bin directory.
I am working with Ubuntu 20.04.
After generating the necessary Ninja files with 
``` cmake -G Ninja ```, I tried to run ```ninja server```.
But I am having some dependency issues. 

![image](https://user-images.githubusercontent.com/49276661/154848208-d2e805a0-2f12-46f5-86bf-d6c1e238cba7.png)

Afterwards, I added them manually, but I couldn't get it to work. 
Did the dependency loaction change over the course of time?
I really hope, you have some advice for me.

Thank you in advance!
Kind Regards

**Comment by larseggert** [comment]
Heh. I never tried the `ninja server` target. If you just run `ninja`, does that work for you?

**Comment by sercankoc** [comment]
Thanks for your fast response!

Yes, i tried that. But it still shows me, that it can't find the directories.
I only tried to mimic your actions in ```test.sh```.

![image](https://user-images.githubusercontent.com/49276661/155027184-0a2fe232-9fe1-44c9-899c-4b497cd20b3f.png)

The CMake only includes those two directories though.
I haven't changed anything and I even redownloaded the /bin directory.
![image](https://user-images.githubusercontent.com/49276661/155027157-e4738108-a53f-449a-ba66-cb9b51501dfd.png)
I hope, I'm not doing something fatally and obviously wrong.
As addiontal information:
I want a simple server, that the Riot QUIC Client can connect with. As you stated in the example, it only works locally.
Thanks in advance!

**Comment by larseggert** [comment]
Did you follow the steps in the `README`? Specifically, did you run `git submodule update --init --recursive`?

**Comment by sercankoc** [comment]
Yes, I did. I redid all steps as well, just to be safe.
I guess, I should rather run the server with docker and try use it with the Riot Client?

**Comment by larseggert** [comment]
Can you attach a terminal log of what you're doing an what output is generated, starting with `git clone`?

**Comment by sercankoc** [comment]
I used a bash script for the installation and just run that
[script.txt](https://github.com/NTAP/quant/files/8127956/script.txt)
[git.txt](https://github.com/NTAP/quant/files/8127957/git.txt)
.

**Comment by larseggert** [comment]
Thanks for that! But I don't see any error message in `git.txt`, looks like the build succeeded?

**Comment by sercankoc** [comment]
Yes it did! It's really just the issue, that it can't find dependencies it needs, when i want to compile it.

**Comment by larseggert** [comment]
But the log you posted shows that it **did** compile?

**Comment by larseggert** [comment]
@sercankoc can you confirm that the build you showed in `git.log` worked?

**Comment by sercankoc** [comment]
> @sercankoc can you confirm that the build you showed in `git.txt` worked?

Yes, it worked. The Debug directory is here...
And as I'm writing this, I found out I did something fundamentally wrong, as I thought.
It is embarrassing to admit, but I tried to get the /bin directory to work instead of /Debug/bin.
I apologize for taking up so much of your time for this.

It works now...
Thank you!
