### ISSUE TITLE
empty version negotiation packet

### ISSUE THREAD

**Issue by marten-seemann** [NTAP/quant#9]
When hitting the public endpoint with an unsupported version, I'm getting an empty version negotiation packet (17 bytes long, which means the header seems correct, but it contains no versions at all).

**Comment by marten-seemann** [comment]
Just saw that the format of the VNP was changed again, and it now doesn't contain a packet number. Sorry for the incorrect bug report.

**Comment by larseggert** [comment]
Yeah, those constant changes to the basic mechanisms of the protocol are annoying
